# My particular dns.palladius.eu project
gce:
  project:  biglamp
  hostname: denise-ng
  tags:
  - dns
  - prod
  - 1
  - 3
project:
 name: denise.palladius.eu
 description: my personal public DNS
 type: dns
 source: here
 destination: denise.google.palladius.eu
 #init.script: boot.sh
foo: bar