#############################
# dns.palladius.eu project  #
#############################
gce:
  project:  biglamp
  hostname: denise-ng
  tags:
  - dns
  - prod
  metadata:
    startup-script: 'projects/dns.palladius.eu/first-boot.sh'
project:
 name: denise.palladius.eu
 description: my personal public DNS
 type: dns
 source: here
 destination: denise.google.palladius.eu
private:
  foo: bar
# TODO implement it
gcutil:
  firewall:
    name: allow-dns
    allowed: 
    - tcp:53
    - udp:53