#############################
# dns.palladius.eu project  #
#############################
gce:
  project:  biglamp
  hostname: gwww-goliardia
  tags:
  - www
  - prod
  - goliardia
#  metadata:
#    startup-script: 'projects/{{project}}/first-boot.sh'
project:
 name: www.goliardia.it
 description: my Goliardia site has gone Google!
 type: www
private:
  palladius-pwd: TODO
backups:
 db: gs://rcarlesso/openprojects/www.goliardia.it/backup/db/
 code: 
files:
 - gs://rcarlesso-openprojects/www.goliardia.it/db/goliardia-solstizio12-Sql33291_1.sql.zip
# TODO implement it
gcutil:
  firewall:
    name: allow-www
    allowed: 
    - tcp:80
    - tcp:443
