##############################################
# DO NOT CHANGE
#
# This contains a YML of default info. Overwrite this
# with your peculiar project.yml in your project dir
##############################################
gce:
  project:  YOUR_PROJECT_IS_MANDATORY
  hostname: YOUR_HOSTNAME
  init-script: boot.sh
  network:  default
  project-base: google.com
  zone: us-east1-a   
  machine-type: n1-standard-1   
  tags:
  - dflt
  metadata:
    ric-description: I am a default metadata description common to all Riccardo projects
    description: feel free to change this instead
    startup-script: 'projects/{{project}}/first-boot.sh'
    common: io all
    project: '{{project}}'
foo: baz
project:
  name: _MANDATORY_
  description: Put your description here...